# Default values for nginx-example.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  tag: latest

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 30571

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
