apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-example.name" . }}-cm
data:
  index.html: |
    <html>
      <head>
        <title>Example page</title>
      </head>
      <body>
        <h1>This page is served via Nginx!</h1>
      </body>
    </html>

